server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    server_name _;

    # Compresión para que el sitio cargue más rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location / {
        try_files $uri /index.html;
    }

    # Caché para archivos estáticos (opcional pero recomendado)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}